[server]
headless = true
maxUploadSize = 300

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#167A6C"
backgroundColor = "#F3F6F5"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#142725"
font = "sans serif"
